### model
model_name_or_path: /data/coding/Qwen2.5-VL-7B-Instruct


trust_remote_code: False
image_max_pixels: 262144
freeze_vision_tower: False
freeze_multi_modal_projector: False


#quantization_bit: 8  # choices: [8 (bnb/hqq/eetq), 4 (bnb/hqq), 3 (hqq), 2 (hqq)]
#quantization_method: bnb


### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
loraplus_lr_ratio: 16.0
use_muon: true
#use_unsloth: true
#use_unsloth_gc: true


### dataset
dataset: caption  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 2048
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 16

### output
output_dir: saves/qwen2_vl-7b/lora/caption
logging_steps: 5
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 6
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
#val_size: 0.05
eval_dataset: test_data_extra
per_device_eval_batch_size: 6
eval_strategy: steps
eval_steps: 500

flash_attn: fa2
#use_unsloth: True